version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    networks:
      - internal
    depends_on:
      - app
    volumes:
      - ./app:/var/www/html:ro
      - ./log/nginx:/var/log/nginx:rw
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  app:
    build:
      context: app
      dockerfile: Dockerfile
    networks:
      - internal
    depends_on:
      - database
    environment:
      - APP_ENV=${APP_ENV:-dev}
      - APP_SECRET=${APP_SECRET:?error}
      - DATABASE_URL="postgresql://${DATABASE_USER:-app}:${DATABASE_PASSWORD:?error}@database:5432/${DATABASE_DB:-app}?serverVersion=15&charset=utf8"
    volumes:
      - ./app:/var/www/html:rw
      - ./log/app:/var/www/html/var/log:rw
      - storage_app:/var/www/html/var/storage:rw


  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    networks:
      - internal
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DATABASE_DB:-app}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:?error}
      POSTGRES_USER: ${DATABASE_USER:-app}
    volumes:
      - storage_database:/var/lib/postgresql/data:rw

networks:
  internal:
    driver: bridge

    # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
    # - ./docker/db/data:/var/lib/postgresql/data:rw
##< doctrine/doctrine-bundle ###

volumes:
  storage_app:
  storage_database: